module.exports = Object.freeze({
    PUBLISHED: 'PUBLISHED',
    DRAFT: 'DRAFT',
    DEFAULT_NO_OF_RESULTS: 5,
    LENGTH_OF_EACH_TAG: 15,
    TOTAL_TAG: 5,
    BLOG_TITLE_LENGTH: 70,
    DISCUSSION_TITLE_LENGTH: 70,
    POST_CONTENT_LENGTH: 255,
    TAG_LENGTH_FOR_AUTOPOPULATING: 3
});